apiVersion: v1
kind: Service
metadata:
  name: k3s-info-resilient
  namespace: demo-k3s
spec:
  selector:
    app: k3s-info-resilient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  publishNotReadyAddresses: false  
